services:
  tfidf_svc:
    build: ./services/tfidf_svc
    image: mini-mlops/tfidf_svc:local
    environment:
      - MODEL_PATH=/app/model/model.joblib
    volumes:
      - ./artifacts/tfidf:/app/model:ro     
    ports: ["8001:8001"]

  transformer_svc:
    build: ./services/transformer_svc
    image: mini-mlops/transformer_svc:local
    environment:
      - MODEL_DIR=/app/model
    volumes:
      - ./artifacts/transformer:/app/model:ro 
    ports: ["8002:8002"]

  agent_svc:
    build: ./services/agent_svc
    image: mini-mlops/agent_svc:local
    environment:
      - TFIDF_URL=http://tfidf_svc:8001/predict
      - TRANSFORMER_URL=http://transformer_svc:8002/predict
    depends_on:
      - tfidf_svc
      - transformer_svc
    ports:
      - "8000:8000"






