stages:
  prepare:
    cmd: python -m training.prepare.prepare
    deps:
      - data/raw
      - training/prepare/prepare.py
    outs:
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv

  train_tfidf:
    cmd: python -m training.tfidf.train
    deps:
      - data/processed/train.csv
      - data/processed/val.csv
      - training/tfidf/train.py
      - models/tfidf.py
      - models/__init__.py
    outs:
      - artifacts/tfidf/model.joblib
      - artifacts/tfidf/labels.json
      - artifacts/tfidf/classification_report_val.json

  train_transformer:
    cmd: python -m training.transformer.train
    deps:
      - data/processed/train.csv
      - data/processed/val.csv
      - training/transformer/train.py
      - models/transformers.py
      - models/__init__.py
    outs:
      - artifacts/transformer
