stages:
  prepare:
    cmd: python -m training.prepare.prepare
    deps:
      - training/prepare/prepare.py
      - data/raw/tickets.csv
    outs:
      - data/processed/train.pkl
      - data/processed/val.pkl
      - data/processed/test.pkl

  train_tfidf:
    cmd: python -m training.tfidf.train
    deps:
      - training/tfidf/train.py
      - models/tfidf.py
      - models/__init__.py
      - data/processed/train.pkl
      - data/processed/val.pkl
      - data/processed/test.pkl
    outs:
      - artifacts/tfidf/model.joblib
    metrics:
      - artifacts/tfidf/classification_report.json


  train_transformer:
    cmd: python -m training.transformer.train
    deps:
      - training/transformer/train.py
      - models/transformers.py
      - models/__init__.py
      - data/processed/train.pkl
      - data/processed/val.pkl
      - data/processed/test.pkl
    outs:
      - artifacts/transformer/needed_files
