global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "agent_svc"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "agent_svc:8080"


  - job_name: "tfidf_svc"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "tfidf_svc:8081"


  - job_name: "transformer_svc"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "transformer_svc:8082"
